package generator

import (
	"fpk-compose-builder/internal/parser"
)

// MainScriptTemplate is the default cmd/main script template
// It handles start/stop/status for docker-compose based applications
const MainScriptTemplate = `#!/bin/bash
# Generated by fpk-compose-builder
# Container: {{CONTAINER_NAME}}

FILE_PATH="${TRIM_APPDEST}/docker/docker-compose.yaml"

is_docker_running() {
    DOCKER_NAME=""
    if [ -f "$FILE_PATH" ]; then
        DOCKER_NAME=$(cat $FILE_PATH | grep "container_name" | awk -F ':' '{print $2}' | xargs)
    fi
    if [ -n "$DOCKER_NAME" ]; then
        docker inspect $DOCKER_NAME 2>/dev/null | grep -q '"Status": "running"' && return 0
    fi
    return 1
}

case $1 in
start)
    # Container lifecycle is managed by Docker/fnOS docker-project
    exit 0
    ;;
stop)
    # Container lifecycle is managed by Docker/fnOS docker-project
    exit 0
    ;;
status)
    # Check if container is running via docker inspect
    is_docker_running && exit 0 || exit 3
    ;;
*)
    exit 1
    ;;
esac
`

// LifecycleScripts defines all lifecycle scripts that should be generated
// These scripts are called at various points during app installation/configuration
var LifecycleScripts = map[string]string{
	"install_init": `#!/bin/bash
# Generated by fpk-compose-builder
# This script is called before the user installs the application.

exit 0
`,
	"install_callback": `#!/bin/bash
# Generated by fpk-compose-builder
# This script is called after the user installs the application.

exit 0
`,
	"uninstall_init": `#!/bin/bash
# Generated by fpk-compose-builder
# This script is called before the user uninstalls the application.

exit 0
`,
	"uninstall_callback": `#!/bin/bash
# Generated by fpk-compose-builder
# This script is called after the user uninstalls the application.

exit 0
`,
	"upgrade_init": `#!/bin/bash
# Generated by fpk-compose-builder
# This script is called before the user upgrades the application.

exit 0
`,
	"upgrade_callback": `#!/bin/bash
# Generated by fpk-compose-builder
# This script is called after the user upgrades the application.

exit 0
`,
	"config_init": `#!/bin/bash
# Generated by fpk-compose-builder
# This script is called before the user changes environment variables in application setting page.

exit 0
`,
	"config_callback": `#!/bin/bash
# Generated by fpk-compose-builder
# This script is called after the user changes environment variables in application setting page.

exit 0
`,
}

// GenerateMainScript generates the cmd/main bash script
// The script handles start/stop/status commands for docker-compose applications
func GenerateMainScript(vars parser.Variables) string {
	// Replace the container name placeholder
	script := MainScriptTemplate
	script = ReplaceVariables(script, parser.Variables{
		ServiceName:   vars.ServiceName,
		ContainerName: vars.ContainerName,
		FirstPort:     vars.FirstPort,
	})

	// Replace the {{CONTAINER_NAME}} template variable
	script = replaceTemplateVar(script, "CONTAINER_NAME", vars.ContainerName)

	return script
}

// GenerateLifecycleScripts returns all lifecycle scripts
func GenerateLifecycleScripts() map[string]string {
	return LifecycleScripts
}

// replaceTemplateVar replaces {{VAR}} style template variables
func replaceTemplateVar(content, varName, value string) string {
	placeholder := "{{" + varName + "}}"
	result := content
	for i := 0; i < len(result); i++ {
		idx := indexOf(result, placeholder)
		if idx == -1 {
			break
		}
		result = result[:idx] + value + result[idx+len(placeholder):]
	}
	return result
}

// indexOf finds the index of substr in s, returns -1 if not found
func indexOf(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
